# Travis CI (http://travis-ci.org/) is a continuous integration
# service for open source projects. This file configures it
# to run unit tests for go-nmea.

language: go

go:
    - 1.11.x
    - 1.12.x
    - 1.13.x
    - 1.14.x
    - tip

matrix:
    fast_finish: true

before_install:
    - go install golang.org/x/lint/golint
    - go install github.com/mattn/goveralls

script:
    - go vet -x ./...
    - golint -set_exit_status ./...
    - go test -v -race -covermode=atomic -coverprofile=profile.cov ./...

after_script:
    - goveralls -coverprofile=profile.cov -service=travis-ci
